service: stecu-great-ai

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${self:provider.stage}
    NOTARIZE_URL: ${env:NOTARIZE_URL, 'https://2f2279683902.ngrok-free.app/notarize'}
  timeout: 30
  memorySize: 256

functions:
  notarize:
    handler: lambda/notarize.handler
    events:
      - http:
          path: /api/notarize
          method: post
          cors: true
    environment:
      NOTARIZE_URL: ${env:NOTARIZE_URL, 'https://2f2279683902.ngrok-free.app/notarize'}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
